### ISSUE TITLE
想添加一些优化理论的书，如何上传进去呢？

### ISSUE THREAD

**Issue by lingr7** [loveunk/Deep-learning-books#1]
[凸优化 · 语雀 ](https://www.yuque.com/lingr7/blog/mdhntc) 
我放在了语雀上，但是还是放在github上要好一点

**Comment by loveunk** [comment]
@lingr7 你可以submit pull request，然后我merge进repo。如果不是很熟悉如何操作的话，请告诉我你需要contribute哪些pdf？谢谢

**Comment by lingr7** [comment]
本来想熟悉一下操作的，发现这个仓库文件好多好大，下载龟速，主要是《最优化导论》（第四版）别的，这里面应该都有了。

**Comment by loveunk** [comment]
@lingr7 最近在内地用GitHub确实遇到速度问题。我下班后来upload《最优化导论》，谢谢啦
