### ISSUE TITLE
有没有其他源

### ISSUE THREAD

**Issue by yiyinying** [loveunk/Deep-learning-books#4]
github上下不了，能不能给个百度盘什么的

**Comment by 610yilingliu** [comment]
我绕了一圈用AWS服务器下载了。远程连接到aws——在aws上安装git——git clone到AWS服务器——scp从aws服务器传输到本地

**Comment by 610yilingliu** [comment]
> github上下不了，能不能给个百度盘什么的

顺手在medium记了个小教程
https://medium.com/@yilingliu1994/download-files-from-github-through-aws-server-68fde8be5aef
使用ShadowSocksR下载会断开，不知道怎么回事。

**Comment by loveunk** [comment]
> github上下不了，能不能给个百度盘什么的

Visit the "raw" page and scroll to the end, then you will find the links for Dropbox and BaiduYun:
https://raw.githubusercontent.com/loveunk/Deep-learning-books/master/README.md
